name: PVCat Automation Bot

on:
  schedule:
    # Entrada 10:00 Spain Time (09:00 UTC)
    - cron: '0 9 * * 1-4'
    
    # Sortida 17:00 Spain Time (16:00 UTC)
    - cron: '0 16 * * 1-4'
    
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

jobs:
  punch-clock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Execute punch-clock script
        env:
          # Make sure to set these in Settings > Secrets and variables > Actions
          USER_PVCAT: ${{ secrets.USER_PVCAT }}
          PASS_PVCAT: ${{ secrets.PASS_PVCAT }}
        run: python fichar.py
